name: Test
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    if: >
      ${{
        contains(github.event.head_commit.message, '[MAJOR]') ||
        contains(github.event.head_commit.message, '[MINOR]') || 
        contains(github.event.head_commit.message, '[PATCH]')
      }}
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"